sudo: required
services:
  - docker

before_install:
  - docker build -t anshulchanchlani/docker-react -f Dockerfile.dev .

script:
  -  docker run anshulchanchlani/docker-react npm run test -- --coverage

deploy: 
  provider: elasticbeanstack
  region: "ap-south-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-434941217266"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
  